# Generated by Django 6.0.1 on 2026-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetryupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryupload',
            name='datafile',
            field=models.FileField(blank=True, null=True, upload_to='telemetry/%Y/%m/'),
        ),
    ]
