# Generated by Django 6.0.1 on 2026-04-29 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_telemetryupload_datafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryrecord',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='telemetry.telemetryupload'),
        ),
    ]
