# Generated by Django 6.0.1 on 2026-04-29 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_telemetryrecord_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField()),
                ('anomaly_count', models.IntegerField()),
                ('f1_score', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('auc_roc', models.FloatField(blank=True, null=True)),
                ('confusion_matrix', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
